# This is a basic workflow to help you get started with Actions

name: Package deploy CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vbump.outputs.version }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: bumping version
      id: vbump
      run: echo "::set-output name=version::$(npm --no-git-tag-version version minor)"

    - name: install dependencies
      run: npm ci

    - name: compile package
      run: npm run compile

    - name: publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}

    - name: committing version bump
      run: |
        git config user.email "dominik.sander.monster@gmail.com"
        git config user.name "Dominik Sander"
        git add -A
        git commit -m "Bumped version to ${{ steps.vbump.outputs.version }}"
        git push

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vbump.outputs.version }}
        release_name: Release ${{ steps.vbump.outputs.version }}
        draft: false
        prerelease: false
